# Generated by Django 4.1.3 on 2023-02-19 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_token_residenttoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResidentToken',
        ),
    ]
